// This stores constant for productList. A central place for all constants

export const PRODUCT_LIST_REQUEST ="PRODUCT_LIST_REQUEST" ;
export const PRODUCT_LIST_SUCCESS ="PRODUCT_LIST_SUCCESS" ;
export const PRODUCT_LIST_FAIL ="PRODUCT_LIST_FAIL" ;


// Constants for Product details
export const PRODUCT_DETAILS_REQUEST ="PRODUCT_DETAILS_REQUEST" ;
export const PRODUCT_DETAILS_SUCCESS ="PRODUCT_DETAILS_SUCCESS" ;
export const PRODUCT_DETAILS_FAIL ="PRODUCT_DETAILS_FAIL" ;

// Constants for Product delete
export const PRODUCT_DELETE_REQUEST ="PRODUCT_DELETE_REQUEST" ;
export const PRODUCT_DELETE_SUCCESS ="PRODUCT_DELETE_SUCCESS" ;
export const PRODUCT_DELETE_FAIL ="PRODUCT_DELETE_FAIL" ;

// Constants for creating new product
export const PRODUCT_CREATE_REQUEST ="PRODUCT_CREATE_REQUEST" ;
export const PRODUCT_CREATE_SUCCESS ="PRODUCT_CREATE_SUCCESS" ;
export const PRODUCT_CREATE_FAIL ="PRODUCT_CREATE_FAIL" ;
export const PRODUCT_CREATE_RESET ="PRODUCT_CREATE_RESET" ;